
spring:
  application:
    name: ServiceSupport
  datasource:
    url: jdbc:mysql://localhost:3306/servicedesk?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: servicedesk
    password: servicedesk
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    drop-first: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: szakdogaprogram@gmail.com
    password: ydra zhcd xiqp omhl  # ⚠️ Google fiókhoz "App password" kell, nem sima jelszó SzakdogaProgram1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

