services:
  db:
    image: mysql:8.4
    container_name: servicedesk-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servicedesk
      MYSQL_USER: servicedesk
      MYSQL_PASSWORD: servicedesk
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: servicedesk-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

  backend:
    image: delano0b/servicesupport_be_v1:latest
    container_name: servicedesk-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/servicedesk
      SPRING_DATASOURCE_USERNAME: servicedesk
      SPRING_DATASOURCE_PASSWORD: servicedesk
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: delano0b/servicesupport_fe_v1:latest
    container_name: servicedesk-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    ports:
      - "4200:80"